export const LIMITS = {
  // Activity Tracker
  DEBOUNCE_ACTIVE_MS: 500,
  IDLE_WARNING_SECONDS: 180,
  AUTO_PAUSE_CUTOFF_SECONDS: 300,
  HEARTBEAT_INTERVAL_MS: 1000,
  SNAPSHOT_INTERVAL_SECONDS: 10,

  // Graph Physics & Shaders
  FORCE_PULSE_HZ: 1.2,
  PHOTON_PARTICLE_SPEED_PX_SEC: 40,
  LOD1_ZOOM_MAX: 0.4,
  LOD2_ZOOM_MAX: 1.0,

  // Spaced Repetition & Streaks
  MIN_FOCUS_SECONDS_FOR_STREAK: 900, // 15 mins
  MIN_REVIEWS_FOR_STREAK: 10,
  STREAK_FREEZE_INTERVAL_DAYS: 14,

  // Colors
  COLORS: {
    EMERALD_GLOW: '#10B981',
    CYAN_PARTICLE: '#38BDF8',
    P1_RED: '#EF4444',
    P2_YELLOW: '#F59E0B',
    P3_GREEN: '#10B981'
  }
}
